name: "User Story"
description: "Erstelle eine neue User Story"
title: "Als [Rolle] möchte ich [Ziel], um [Nutzen]"
labels: ["user story"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Beschreibe, was der User tun möchte und warum.
  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      description: Liste die Bedingungen auf, wann die Story als fertig gilt.
  - type: textarea
    id: notes
    attributes:
      label: Notizen
      description: Optional: Design, technische Hinweise, etc.
