name: User Story
description: Erstelle eine neue User Story
title: "[USER STORY] "
labels: ["user story"]
body:
  - type: textarea
    id: description
    attributes:
      label: Beschreibung
      description: Beschreibe, was der User tun möchte und warum.
      placeholder: "Als [Rolle] möchte ich [Ziel], um [Nutzen]."
    validations:
      required: true

  - type: textarea
    id: acceptance
    attributes:
      label: Akzeptanzkriterien
      description: Liste die Bedingungen auf, wann die Story als fertig gilt.
      placeholder: |
        - [ ] Kriterium 1
        - [ ] Kriterium 2
    validations:
      required: true

  - type: textarea
    id: notes
    attributes:
      label: Notizen
      description: Optional - Design, technische Hinweise, etc.
    validations:
      required: false
