# Production profile
spring:
  config:
    activate:
      on-profile: prod

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  datasource:
    hikari:
      maximum-pool-size: 50
      minimum-idle: 10

  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: ${HOST}/realms/safenet/protocol/openid-connect/token/introspect
          client-id: ${KEYCLOAK_CLIENT_ID}
          client-secret: ${KEYCLOAK_CLIENT_SECRET}

logging:
  level:
    root: WARN
    com.hackathon.safenet: INFO
    org.springframework.security: INFO