# Development profile
spring:
  config:
    activate:
      on-profile: dev

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${HOST}:8081/realms/safenet
          jwk-set-uri: ${HOST}:8081/realms/safenet/protocol/openid-connect/certs

logging:
  level:
    com.hackathon.safenet: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.security.oauth2.server.resource: TRACE
    org.springframework.security.web.authentication: DEBUG
    org.springframework.boot.autoconfigure.security.oauth2: DEBUG